# Generated by Django 4.2.1 on 2025-05-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='期刊名称')),
                ('level', models.CharField(max_length=50, verbose_name='等级')),
            ],
        ),
    ]
